# Generated by Django 4.2.3 on 2023-08-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_connect', '0003_remove_property_tenants'),
        ('user_auth', '0002_landlord_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='landlord',
        ),
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_connect.property'),
        ),
    ]
