# Generated by Django 4.2.3 on 2023-08-11 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0002_landlord_tenant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='landlord',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.profile'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.profile'),
        ),
    ]
