# Generated by Django 4.2.3 on 2023-08-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_tenant_landlord_tenant_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
    ]
