# Generated by Django 4.2.3 on 2023-08-21 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0003_rename_userprofile_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='profile',
        ),
        migrations.AddField(
            model_name='landlord',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
