# Generated by Django 4.2.3 on 2023-08-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_connect', '0007_alter_invitation_property_alter_invitation_tenant_and_more'),
        ('user_auth', '0004_remove_landlord_user_remove_tenant_property_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Landlord',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
