# Generated by Django 4.2.3 on 2023-08-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_landlord_tenant'),
        ('user_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='tenants', to='user_auth.tenant'),
        ),
    ]
