# Generated by Django 4.2.3 on 2023-08-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_connect', '0002_alter_property_tenants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tenants',
        ),
    ]
