# Generated by Django 4.2.3 on 2023-08-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_tenant_landlord_tenant_property'),
        ('user_connect', '0003_remove_property_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Landlord', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.landlord')),
                ('property', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_connect.property')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.tenant')),
            ],
        ),
    ]
