# Generated by Django 4.2.3 on 2023-08-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_connect', '0004_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='Landlord',
        ),
    ]
