# Generated by Django 4.2.3 on 2023-08-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_tenant_landlord_tenant_property'),
        ('user_connect', '0005_remove_invitation_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_connect.property'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.tenant'),
        ),
    ]
